---
################################################################################
#                                  Jose.Lima                                   #
#                     Network Optimization and Automation                      #
################################################################################

- name: 'install pip packages'
  hosts: localhost
  gather_facts: no

  tasks:
    - name: install venv
      pip:
        name:
          - pip
        state: latest
        virtualenv: ~/.virtualenvs/project_env
        virtualenv_command: python3 -m venv

    - name: install venv
      pip:
        name:
          - ansible==2.9.13
          - pytest
          - ansible-lint==4.3.7
        virtualenv: ~/.virtualenvs/project_env
        virtualenv_command: python3 -m venv
